apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
      - name: app
        image: node:14-alpine
        command: ["node", "-e", "require('http').createServer((req, res) => res.end('Hello from Node!')).listen(3000);"]
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: multi-container-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: node-port
      port: 3000
      targetPort: 3000
      nodePort: 30002
  selector:
    app: multi-container
